In [50]:
# Задание 1
import numpy as np
import pandas as pd

In [51]:
from sklearn.datasets import load_boston

In [52]:
boston = load_boston()

In [53]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [54]:
data = boston.data
data.shape

(506, 13)

In [55]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [56]:
feature_names = boston.feature_names
X = pd.DataFrame(data, columns=feature_names)

In [57]:
X.shape

(506, 13)

In [58]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB

In [59]:
target = boston.target
y = pd.DataFrame(target, columns=['Price'])
target.shape

(506,)

In [60]:
y.head()

   Price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [61]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   506 non-null    float64
dtypes: float64(1)
memory usage: 4.1 KB

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size = 0.30, random_state=42)

In [64]:
from sklearn.linear_model import LinearRegression

In [65]:
lr = LinearRegression()

In [66]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
y_pred = lr.predict(X_test)

In [68]:
check_test = pd.DataFrame({'y_test':y_test['Price'], 'y_pred':y_pred.flatten()},columns=['y_test', 'y_pred'])

In [69]:
check_test.head(15)

     y_test     y_pred
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280
76     20.0  23.146689
316    17.8  17.392124
140    14.0  14.078599
471    19.6  23.036927
500    16.8  20.599433
218    21.5  24.822862
9      18.9  18.530570
414     7.0  -6.865435
78     21.2  21.801723
323    18.5  19.225712

In [70]:
from sklearn.metrics import r2_score

In [71]:
r2_score1 = r2_score(y_test, y_pred)
r2_score1

0.7112260057484974

In [72]:
# Задание 2
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, max_depth=12, random_state=42)

In [73]:
model.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=12, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [74]:
y_pred = model.predict(X_test)

In [75]:
check_test = pd.DataFrame({'y_test':y_test['Price'], 'y_pred':y_pred.flatten()},columns=['y_test', 'y_pred'])

In [76]:
check_test.head(15)

     y_test     y_pred
173    23.6  23.156214
274    32.4  31.199000
491    13.6  16.011514
72     22.8  24.227608
452    16.1  16.940542
76     20.0  21.847517
316    17.8  19.732158
140    14.0  14.911167
471    19.6  21.508747
500    16.8  21.239091
218    21.5  19.805309
9      18.9  20.370592
414     7.0   8.050000
78     21.2  21.343033
323    18.5  19.327681

In [77]:
r2_score2 = r2_score(y_test, y_pred)
r2_score2

0.8691643189868505

In [78]:
#Ошибка в предсказании второй модели ниже чем в первой

In [79]:
# Задание 3
?RandomForestRegressor

In [80]:
print(model.feature_importances_)

[0.03177896 0.00158242 0.00646271 0.0017163  0.01197879 0.43972879
 0.01160458 0.06602488 0.00504852 0.01167048 0.02062718 0.01151466
 0.38026172]

In [81]:
model.feature_importances_.sum()

1.0

In [84]:
#визуально это 6 и 13 признак
print(model.feature_importances_[5])
print(model.feature_importances_[12])

0.4397287873337628
0.38026172322612045

In [86]:
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
visual_info = pd.Series(model.feature_importances_)
visual_info.plot(kind='bar')
plt.show()

In [87]:
# Задание 4
DATASET_PATH = 'creditcard.csv'
df = pd.read_csv(DATASET_PATH)
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [88]:
from sklearn.ensemble import RandomForestClassifier

In [90]:
from sklearn.model_selection import GridSearchCV

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
df['Class'].value_counts(normalize=True)

0    0.998273
1    0.001727
Name: Class, dtype: float64

In [94]:
pd.options.display.max_columns = 100

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [96]:
df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,1.341262,0.359894,-0.358091,-0.137134,0.517617,0.401726,-0.058133,0.068653,-0.033194,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,-1.416907,-0.153826,-0.751063,0.167372,0.050144,-0.443587,0.002821,-0.611987,-0.045575,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,1.249376,-0.619468,0.291474,1.757964,-1.323865,0.686133,-0.076127,-1.222127,-0.358222,0.324505,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,-0.705117,-0.110452,-0.286254,0.074355,-0.328783,-0.210077,-0.499768,0.118765,0.570328,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,1.017614,0.836390,1.006844,-0.443523,0.150219,0.739453,-0.540980,0.476677,0.451773,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [97]:
X = df.drop('Class', axis=1)
X.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,1.341262,0.359894,-0.358091,-0.137134,0.517617,0.401726,-0.058133,0.068653,-0.033194,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,-1.416907,-0.153826,-0.751063,0.167372,0.050144,-0.443587,0.002821,-0.611987,-0.045575,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,1.249376,-0.619468,0.291474,1.757964,-1.323865,0.686133,-0.076127,-1.222127,-0.358222,0.324505,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,-0.705117,-0.110452,-0.286254,0.074355,-0.328783,-0.210077,-0.499768,0.118765,0.570328,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,1.017614,0.836390,1.006844,-0.443523,0.150219,0.739453,-0.540980,0.476677,0.451773,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68

In [100]:
y = df['Class']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [101]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size = 0.30, random_state=100, stratify=y)

In [103]:
X_train, X_test, y_train, y_test

(            Time        V1        V2        V3        V4        V5        V6  \
 222925  143180.0  2.053474 -0.149880 -1.092234  0.420978 -0.225796 -1.159629
 163811  116231.0  0.149477  1.112008 -0.391539 -0.557452  1.014727 -0.801985
 196038  131332.0  2.145379  0.215237 -2.221643 -0.067032  0.815822 -1.358596
 25173    33527.0 -0.354219  0.100332  1.721509 -0.884417 -0.371977 -0.062313
 253792  156421.0 -0.439888  1.871311 -1.106687  1.064853  1.239594 -0.633668
 ...          ...       ...       ...       ...       ...       ...       ...
 194533  130633.0 -0.917471  0.855403  1.516046 -0.220692  0.747332  0.859372
 163532  116011.0 -0.818922 -0.653837  1.685615 -1.561367  0.357487  1.306132
 47169    43114.0  0.984295 -0.951871  0.760848  0.729305 -1.429835 -0.353366
 138367   82618.0  0.699525 -1.558081  0.286748  0.349547 -1.519666 -0.535495
 271        192.0 -0.351287  1.183754  0.530794  0.543891  0.798441 -0.804472

               V7        V8        V9       V10       V11       V12       V13  \
 222925  0.082871 -0.236532  0.733270  0.102520 -0.908262 -0.220082 -1.216003
 163811  1.042734 -0.167625 -0.200830 -0.863839 -0.537991  0.418586  1.034272
 196038  0.843943 -0.594243  0.009745 -0.021497 -0.476749  0.848265  1.144607
 25173  -0.144740  0.163123 -1.843755  0.520706  1.627755 -0.263976 -0.100123
 253792  1.100319  0.221096 -0.917002 -0.844362 -0.888776 -0.219374 -0.076494
 ...          ...       ...       ...       ...       ...       ...       ...
 194533  0.827820  0.281375  0.400861 -1.066695 -2.440113 -0.765055 -1.608691
 163532  0.371795 -0.086070 -0.349493  0.156626 -0.675390 -1.141582 -0.944494
 47169  -0.542588 -0.063028 -0.419503  0.629828 -0.971147 -0.123702  0.026550
 138367 -0.117706 -0.177233 -0.468385  0.452339 -0.967100 -0.115463 -0.277494
 271     1.563170 -0.935794  0.633634  2.303627  1.398891 -0.318657 -1.410645

              V14       V15       V16       V17       V18       V19       V20  \
 222925  0.534920  0.227331 -0.103995 -0.158785 -0.802113  0.083010 -0.313465
 163811 -1.222412 -0.349818  0.290628  0.298838 -0.333729 -0.226373  0.084311
 196038  0.555759  0.285353 -0.661516 -0.362293 -0.647254  0.126100 -0.133286
 25173   0.125968  0.703573  0.591865  0.665795 -1.191246  1.690163  0.295444
 253792 -0.756161 -0.170227 -0.554555  1.442972  0.385060  0.585502  0.024939
 ...          ...       ...       ...       ...       ...       ...       ...
 194533 -0.233655 -1.496631  0.011731 -0.457877 -0.414743 -0.072057 -0.274203
 163532 -0.998166 -0.265553 -0.894172  1.536807 -2.702692  0.337977  0.072708
 47169  -0.172383  0.361320 -1.416378 -0.041645  1.487895 -1.163956 -0.233008
 138367 -0.071079 -0.190450 -1.633818  0.319327  0.736834 -0.609816  0.116917
 271    -0.155225  0.277950 -0.706228 -0.780092  0.354094  0.618678  0.596401

              V21       V22       V23       V24       V25       V26       V27  \
 222925 -0.298362 -0.779702  0.362701 -0.048183 -0.356438  0.205392 -0.075806
 163811 -0.331768 -0.755443  0.079155  0.587098 -0.383245  0.110292  0.229167
 196038  0.153606  0.611995 -0.027494  0.824538  0.505014  0.203037 -0.083225
 25173   0.136969  0.217167 -0.014350  0.016538 -0.326120 -0.285113  0.118226
 253792  0.059066  0.366613 -0.250861  0.494710  0.091257 -0.398552  0.330173
 ...          ...       ...       ...       ...       ...       ...       ...
 194533 -0.583911 -1.674141 -0.248766 -0.213942  0.609341 -1.054254 -0.068467
 163532  0.248178  1.356247 -0.603728 -1.037884  0.609915  0.318683 -0.277412
 47169  -0.148347 -0.163503 -0.190719  0.378213  0.456626 -0.239030  0.045741
 138367 -0.456747 -1.458638 -0.134677  0.368357  0.086125  0.273679 -0.065344
 271    -0.121755  0.668124 -0.057380  0.301398 -0.730946 -0.538616 -0.037212

              V28  Amount
 222925 -0.063325    1.29
 163811  0.086294    2.69
 196038 -0.069468    4.55
 25173   0.103791   19.95
 253792  0.219909    6.30
 ...          ...     ...
 194533  0.048981   34.48
 163532 -0.461930  100.79
 47169   0.061764  170.00
 138367  0.075715  338.40
 271    -0.479956    1.79

 [199364 rows x 30 columns],
             Time        V1        V2        V3        V4        V5        V6  \
 262922  160713.0 -0.548103  1.376074  0.051147  4.300577  1.761938  0.081805
 123418   76919.0  0.437324  1.824381 -2.299325  1.538479  0.791887 -1.414298
 206135  136082.0  2.056846  0.042030 -1.296059  0.368958  0.032669 -1.349797
 273483  165598.0 -0.497480  0.785269  1.695245 -0.644791  0.491553  0.430883
 245758  152894.0  1.611949 -0.938343 -1.200421  0.653356 -0.386518 -0.465937
 ...          ...       ...       ...       ...       ...       ...       ...
 109541   71427.0  1.273667  0.348576  0.155665  0.610139 -0.179551 -0.860330
 41813    40839.0 -0.442064 -1.217388  1.414466 -1.427350  0.945895  4.810729
 16722    28090.0  0.933553 -0.288416  0.398369  0.538503  0.280716  1.657391
 36147    38413.0 -4.099698 -3.287632  1.648931  1.793736  1.698853 -0.483157
 198375  132464.0 -7.161413  5.244866 -7.056295  0.519916  3.918486 -2.482685

                V7         V8        V9       V10       V11       V12  \
 262922   1.788166  -0.302164 -2.941339  1.393164 -1.873436 -1.746983
 123418   0.482083   0.339477 -0.674650 -1.234870  1.881042 -0.195098
 206135   0.334441  -0.463096  0.452703 -0.016376 -0.526324  0.801353
 273483   0.510721   0.053386  0.552390 -0.545978 -1.545755 -0.957582
 245758   0.069881  -0.147945  0.849526  0.005008 -1.033421 -0.111964
 ...           ...        ...       ...       ...       ...       ...
 109541   0.100726  -0.195347  0.020811 -0.291052 -0.347286  0.242342
 41813   -1.657637   1.121731  0.529958  0.344311 -1.165678 -0.613130
 16722   -0.408491   0.596638  0.174499 -0.234109  2.003246  1.568237
 36147   -0.603089   0.271586  0.127974  0.486426  1.213868  0.653035
 198375 -14.996357 -15.904451 -1.835893 -4.195324 -0.599012  2.849676

              V13       V14       V15       V16       V17       V18       V19  \
 262922 -0.852186  1.058096  0.371916 -0.783216  0.322476  0.210874  1.701892
 123418 -0.688822 -2.926057  0.427144  1.279861  2.651797  2.224899 -0.000361
 206135  1.006171  0.303048  0.637776 -0.262217 -0.553146 -0.181507 -0.244297
 273483 -0.913807 -0.066661  1.561068  0.043679 -0.672767  0.650035  1.013564
 245758 -0.645005  0.305443  0.414153  0.183540 -0.410625 -0.207679 -0.171987
 ...          ...       ...       ...       ...       ...       ...       ...
 109541  0.526277 -0.355216  1.094805  0.572843 -0.149382 -0.210053 -0.065830
 41813  -0.028020 -1.823057 -1.339567  0.385304  0.595942 -0.497526  2.165032
 16722  -0.135354  0.244879  0.175965 -1.350302  0.983088 -2.162239 -1.054337
 36147   0.600744 -0.210172  1.429186  0.531294 -0.727684  0.778147  0.518246
 198375 -3.349200  3.432775 -1.566190  1.768522  3.985681  1.689386 -1.590626

              V20       V21       V22       V23       V24       V25       V26  \
 262922  0.451713  0.316647  0.700714 -0.532490 -0.680250  1.232858  0.980223
 123418 -0.009730 -0.077049 -0.170282  0.108469 -0.365513 -0.436975 -0.393859
 206135 -0.167702  0.261879  0.949829 -0.018148  0.109873  0.295611 -0.115295
 273483  0.212146 -0.280792 -0.548862 -0.367317 -0.044278  0.430846 -0.657662
 245758  0.214406  0.081319 -0.184030  0.065733  0.742927 -0.283315  0.172087
 ...          ...       ...       ...       ...       ...       ...       ...
 109541 -0.045382 -0.305978 -0.878975  0.078359 -0.008235  0.270545  0.115470
 41813   0.391646  0.309636  1.298415 -0.227884  1.109008 -0.265818  0.066769
 16722  -0.169897 -0.038509  0.109277  0.095344 -0.983303  0.097938  0.376637
 36147  -1.029740 -0.219962  1.209664  2.771741 -0.317573  0.388055 -0.137592
 198375  2.685353 -7.997422  2.642809 -8.535706 -0.170266 -3.930720 -1.005978

              V27       V28  Amount
 262922 -0.042880  0.053000  101.42
 123418  0.121535 -0.061320    9.99
 206135 -0.015115 -0.054976   10.49
 273483  0.179848 -0.081837    1.00
 245758 -0.091352 -0.009690  227.75
 ...          ...       ...     ...
 109541 -0.022792  0.028417    5.99
 41813  -0.031789 -0.007266   58.50
 16722   0.038959 -0.005783   42.48
 36147   0.776599  0.085259   71.76
 198375 -1.311254  0.237822   86.52

 [85443 rows x 30 columns],
 222925    0
 163811    0
 196038    0
 25173     0
 253792    0
          ..
 194533    0
 163532    0
 47169     0
 138367    0
 271       0
 Name: Class, Length: 199364, dtype: int64,
 262922    0
 123418    0
 206135    0
 273483    0
 245758    0
          ..
 109541    0
 41813     0
 16722     0
 36147     0
 198375    0
 Name: Class, Length: 85443, dtype: int64)

In [106]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((199364, 30), (85443, 30), (199364,), (85443,))

In [107]:
parameters = [{'n_estimators': [10, 15],
'max_features': np.arange(3, 5),
'max_depth': np.arange(4, 7)}]

In [108]:
clf = GridSearchCV(estimator=RandomForestClassifier(random_state=100),param_grid=parameters,scoring='roc_auc',cv=3)

In [109]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=100,
                                              verbose=0, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'max_depth': array([4, 5, 6]),
                          'max_features': array([3, 4]),
                          'n_estimators': [10, 15]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [110]:
clf.best_params_

{'max_depth': 6, 'max_features': 3, 'n_estimators': 15}

In [111]:
y_predict_proba = clf.predict_proba(X_test)
y_predict_proba

array([[9.99070828e-01, 9.29171738e-04],
       [9.99704794e-01, 2.95206364e-04],
       [9.99717846e-01, 2.82154033e-04],
       ...,
       [9.99717846e-01, 2.82154033e-04],
       [9.99317795e-01, 6.82204754e-04],
       [9.87539019e-01, 1.24609813e-02]])

In [112]:
y_pred_proba = y_predict_proba[:,1]

In [113]:
from sklearn.metrics import roc_auc_score

In [114]:
roc_auc_score(y_test, y_pred_proba)

0.9462664156037156

In [115]:
#Дополнительное задание
from sklearn.datasets import load_wine
data = load_wine()

In [120]:
type(data)

sklearn.utils.Bunch

In [121]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [124]:
data_keys = data['feature_names']
data_keys

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [125]:
data.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [126]:
data.data.shape

(178, 13)

In [129]:
print(data['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2

    :Summary Statistics:

    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners:

Forina, M. et al, PARVUS -
An Extendible Package for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science.

.. topic:: References

  (1) S. Aeberhard, D. Coomans and O. de Vel,
  Comparison of Classifiers in High Dimensional Settings,
  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Technometrics).

  The data was used with many others for comparing various
  classifiers. The classes are separable, though only RDA
  has achieved 100% correct classification.
  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))
  (All results using the leave-one-out technique)

  (2) S. Aeberhard, D. Coomans and O. de Vel,
  "THE CLASSIFICATION PERFORMANCE OF RDA"
  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Journal of Chemometrics).

In [133]:
np.unique(data['target']).shape

(3,)

In [134]:
data['target_names']

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [135]:
X = pd.DataFrame(data.data, columns = feature_names)
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [136]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     178 non-null    float64
 1   ZN       178 non-null    float64
 2   INDUS    178 non-null    float64
 3   CHAS     178 non-null    float64
 4   NOX      178 non-null    float64
 5   RM       178 non-null    float64
 6   AGE      178 non-null    float64
 7   DIS      178 non-null    float64
 8   RAD      178 non-null    float64
 9   TAX      178 non-null    float64
 10  PTRATIO  178 non-null    float64
 11  B        178 non-null    float64
 12  LSTAT    178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [137]:
X.shape

(178, 13)

In [157]:
X['target'] = data['target'].astype(np.int64)
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     178 non-null    float64
 1   ZN       178 non-null    float64
 2   INDUS    178 non-null    float64
 3   CHAS     178 non-null    float64
 4   NOX      178 non-null    float64
 5   RM       178 non-null    float64
 6   AGE      178 non-null    float64
 7   DIS      178 non-null    float64
 8   RAD      178 non-null    float64
 9   TAX      178 non-null    float64
 10  PTRATIO  178 non-null    float64
 11  B        178 non-null    float64
 12  LSTAT    178 non-null    float64
 13  target   178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [158]:
X_corr = X.corr()
X_corr

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target
CRIM,1.000000,0.094397,0.211545,-0.310235,0.270798,0.289101,0.236815,-0.155929,0.136698,0.546364,-0.071747,0.072343,0.643720,-0.328222
ZN,0.094397,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011,0.437776
INDUS,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626,-0.049643
CHAS,-0.310235,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597,0.517859
NOX,0.270798,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351,-0.209179
RM,0.289101,-0.335167,0.128980,-0.321113,0.214401,1.000000,0.864564,-0.449935,0.612413,-0.055136,0.433681,0.699949,0.498115,-0.719163
AGE,0.236815,-0.411007,0.115077,-0.351370,0.195784,0.864564,1.000000,-0.537900,0.652692,-0.172379,0.543479,0.787194,0.494193,-0.847498
DIS,-0.155929,0.292977,0.186230,0.361922,-0.256294,-0.449935,-0.537900,1.000000,-0.365845,0.139057,-0.262640,-0.503270,-0.311385,0.489109
RAD,0.136698,-0.220746,0.009652,-0.197327,0.236441,0.612413,0.652692,-0.365845,1.000000,-0.025250,0.295544,0.519067,0.330417,-0.499130
TAX,0.546364,0.248985,0.258887,0.018732,0.199950,-0.055136,-0.172379,0.139057,-0.025250,1.000000,-0.521813,-0.428815,0.316100,0.265668
PTRATIO,-0.071747,-0.561296,-0.074667,-0.273955,0.055398,0.433681,0.543479,-0.262640,0.295544,-0.521813,1.000000,0.565468,0.236183,-0.617369
B,0.072343,-0.368710,0.003911,-0.276769,0.066004,0.699949,0.787194,-0.503270,0.519067,-0.428815,0.565468,1.000000,0.312761,-0.788230
LSTAT,0.643720,-0.192011,0.223626,-0.440597,0.393351,0.498115,0.494193,-0.311385,0.330417,0.316100,0.236183,0.312761,1.000000,-0.633717
target,-0.328222,0.437776,-0.049643,0.517859,-0.209179,-0.719163,-0.847498,0.489109,-0.499130,0.265668,-0.617369,-0.788230,-0.633717,1.000000

In [159]:
high_corr = X_corr['target']
high_corr

CRIM      -0.328222
ZN         0.437776
INDUS     -0.049643
CHAS       0.517859
NOX       -0.209179
RM        -0.719163
AGE       -0.847498
DIS        0.489109
RAD       -0.499130
TAX        0.265668
PTRATIO   -0.617369
B         -0.788230
LSTAT     -0.633717
target     1.000000
Name: target, dtype: float64

In [160]:
high_corr=high_corr[np.abs(high_corr)>0.5].drop('target', axis=0)
high_corr = list(high_corr.index)

In [161]:
high_corr

['CHAS', 'RM', 'AGE', 'PTRATIO', 'B', 'LSTAT']

In [162]:
X=X.drop('target', axis=1)
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [163]:
for name in high_corr:
    X[name+'_2']=X[name]**2

In [164]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,CHAS_2,RM_2,AGE_2,PTRATIO_2,B_2,LSTAT_2
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,243.36,7.8400,9.3636,1.0816,15.3664,1134225.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,125.44,7.0225,7.6176,1.1025,11.5600,1102500.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,345.96,7.8400,10.4976,1.0609,10.0489,1404225.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,282.24,14.8225,12.1801,0.7396,11.9025,2190400.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,441.00,7.8400,7.2361,1.0816,8.5849,540225.0

In [165]:
X.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,CHAS_2,RM_2,AGE_2,PTRATIO_2,B_2,LSTAT_2
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,1.780000e+02
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,391.142865,5.657030,5.110049,0.968661,7.322155,6.564591e+05
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,133.671775,2.936294,4.211441,0.443798,3.584316,5.558591e+05
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,112.360000,0.960400,0.115600,0.230400,1.612900,7.728400e+04
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,295.840000,3.036325,1.452100,0.612325,3.754075,2.505010e+05
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,380.250000,5.546050,4.558250,0.931250,7.728400,4.536045e+05
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,462.250000,7.840000,8.265700,1.254400,10.048900,9.702250e+05
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,900.000000,15.054400,25.806400,2.924100,16.000000,2.822400e+06